### ISSUE TITLE
Waybars don't show correctly

### ISSUE THREAD

**Issue by ohxxm** [DN-debug/waybar-examples#1]
When testing both waybars, each looked different from this:
![](https://github.com/DN-debug/waybar-examples/raw/main/screenshot/swayPost.png)
![](https://github.com/DN-debug/waybar-examples/raw/main/screenshot/wayfire_easyL.png)

**Comment by DN-debug** [comment]
> When testing both waybars, each looked different from this: ![](https://github.com/DN-debug/waybar-examples/raw/main/screenshot/swayPost.png) ![](https://github.com/DN-debug/waybar-examples/raw/main/screenshot/wayfire_easyL.png)

That'll mostly depend on the WM you are running, some modules would work on sway, some would work on wayfire. Edit :Can you post the screenshot of what you are getting at your end?

**Comment by ohxxm** [comment]
> > When testing both waybars, each looked different from this: ![](https://github.com/DN-debug/waybar-examples/raw/main/screenshot/swayPost.png) ![](https://github.com/DN-debug/waybar-examples/raw/main/screenshot/wayfire_easyL.png)
> 
> That'll mostly depend on the WM you are running, some modules would work on sway, some would work on wayfire. Edit :Can you post the screenshot of what you are getting at your end?

I am running sway. I will post a screenshot of my end in a little bit.

**Comment by ohxxm** [comment]
> > When testing both waybars, each looked different from this: ![](https://github.com/DN-debug/waybar-examples/raw/main/screenshot/swayPost.png) ![](https://github.com/DN-debug/waybar-examples/raw/main/screenshot/wayfire_easyL.png)
> 
> That'll mostly depend on the WM you are running, some modules would work on sway, some would work on wayfire. Edit :Can you post the screenshot of what you are getting at your end?

This is what the wayfire bar looks like in sway wm:
![20211218_18h51m43s_grim](https://user-images.githubusercontent.com/68564017/146652749-ed181347-5318-4bb6-ae9c-4e89e7f92006.png)
This is what the sway bar looks like in sway wm:
![20211218_18h57m27s_grim](https://user-images.githubusercontent.com/68564017/146652830-fc33e418-24d0-4f9d-9d8b-ca5a69e68bb5.png)

**Comment by DN-debug** [comment]
I just tested and mine works. 

From what I can see, you are not loading the bar config properly. 
1. With layout2, you'd need to load layout2 style as you are using layout2 config and not the default style as you have done in the below image. Double check what style and config you are loading.



> This is what the wayfire bar looks like in sway wm: ![20211218_18h51m43s_grim](https://user-images.githubusercontent.com/68564017/146652749-ed181347-5318-4bb6-ae9c-4e89e7f92006.png) 

2. Same issue here, you are actually not loading the style or config properly, it is loading the default waybar with default configuration and style as per the image below.

This is what the sway bar looks like in sway wm: ![20211218_18h57m27s_grim](https://user-images.githubusercontent.com/68564017/146652830-fc33e418-24d0-4f9d-9d8b-ca5a69e68bb5.png)


In sway config, use : 

1. For wayfire second layout: `exec --no-startup-id waybar -c ~/.config/waybar/wayfire/layout2/config-wayfire -s ~/.config/waybar/wayfire/layout2/style.css & `
2. For wayfire default layout: `exec --no-startup-id waybar -c ~/.config/waybar/wayfire/config-wayfire -s ~/.config/waybar/wayfire/style.css & `
3. For sway style: `exec --no-startup-id waybar -c ~/.config/waybar/sway/config-sway  -s ~/.config/waybar/sway/sway_style.css &`

Do not forget to put the respective directories inside of `~/.config/waybar `. Edit: Also tweak it as per your liking
